---
project_name: "Mini Corporate Infrastructure Lab"
project_env: "lab"
product_name: "MISIS_Digital Student Support"

admin_ip: "192.168.85.129"
web_ip: "192.168.85.131"
app_ip: "192.168.85.133"
log_ip: "192.168.85.135"
monitor_ip: "192.168.85.137"
db_ip: "192.168.85.139"
windows_vmnet8_ip: "192.168.85.1"

ssh_port: 22

web_http_port: 80
app_api_port: 8080
support_bot_metrics_port: 8090

loki_http_port: 3100
loki_grpc_port: 9095

prometheus_port: 9090
grafana_port: 3000
alertmanager_port: 9093

node_exporter_port: 9100
promtail_metrics_port: 9080

postgres_port: 5432
postgres_exporter_port: 9187

node_exporter_service_name: "prometheus-node-exporter.service"
promtail_service_name: "promtail.service"

loki_push_url: "http://{{ log_ip }}:{{ loki_http_port }}/loki/api/v1/push"

public_web_url: "http://{{ web_ip }}"
public_api_health_url: "http://{{ web_ip }}/api/v1/health"

ansible_managed_note: "Managed by Ansible from admin control-node"
