---
node_role: "app"

docker_service_name: "docker.service"

app_dir: "/opt/app"
compose_project_dir: "/opt/app"
compose_file_path: "/opt/app/docker-compose.yml"
dockerignore_path: "/opt/app/.dockerignore"

app_log_dir: "/var/log/app"
bot_log_dir: "/var/log/bot"

supportdesk_api:
  compose_service_name: "supportdesk-api"
  container_name: "misis-digital-student-support-api"
  image_name: "misis-digital-student-support-api:local"
  env_file: ".env"
  source_files:
    - "app.py"
    - "Dockerfile"
    - "requirements.txt"
  healthcheck_url: "http://localhost:8080/v1/health"
  metrics_url: "http://localhost:8080/metrics"
  external_port: 8080

support_bot:
  compose_service_name: "support-bot"
  container_name: "misis-digital-support-bot"
  image_name: "misis-digital-support-bot:local"
  env_file: ".env.bot"
  source_files:
    - "bot.py"
    - "Dockerfile.bot"
    - "requirements-bot.txt"
  metrics_url: "http://localhost:8090/metrics"
  external_port: 8090

promtail_config_template: "app-promtail.yml.j2"
promtail_config_path: "/etc/promtail/config.yml"
promtail_positions_path: "/var/lib/promtail/positions.yaml"

app_log_paths:
  - "/var/log/app/*.log"

bot_log_paths:
  - "/var/log/bot/*.log"

app_expected_services:
  - "{{ docker_service_name }}"
  - "{{ promtail_service_name }}"
  - "{{ node_exporter_service_name }}"
