---
node_role: "log"

loki_service_name: "loki.service"
loki_config_path: "/etc/loki/config.yml"
loki_data_dir: "/var/lib/loki"
loki_binary_path: "/opt/loki/loki"

loki_ready_url: "http://localhost:3100/ready"

log_expected_services:
  - "{{ loki_service_name }}"
  - "{{ node_exporter_service_name }}"
