server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://192.168.85.135:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx
    pipeline_stages:
      - regex:
          expression: '^(?P<remote_addr>\S+) - (?P<remote_user>\S+) \[(?P<time_local>[^\]]+)\] "(?P<method>\S+) (?P<request_path>\S+) (?P<protocol>[^"]+)" (?P<status_code>\d{3}) (?P<body_bytes_sent>\d+)'
      - labels:
          status_code:
      - metrics:
          nginx_http_responses_total:
            type: Counter
            description: "Total nginx HTTP responses by status code"
            source: status_code
            config:
              action: inc

    static_configs:
      - targets:
          - localhost
        labels:
          host: web
          job: nginx
          service: frontend
          env: lab
          __path__: /var/log/nginx/*.log
