---
- name: Deploy support bot
  hosts: app_nodes
  gather_facts: false
  become: true

  vars_prompt:
    - name: ansible_become_password
      prompt: "BECOME password"
      private: true

  roles:
    - app_compose_project

    - role: docker_compose_service
      compose_service_name: "{{ support_bot.compose_service_name }}"
      compose_source_dir: "{{ playbook_dir }}/../files/bot"
      compose_source_files: "{{ support_bot.source_files }}"
      compose_env_file: "{{ support_bot.env_file }}"
      compose_metrics_url: "{{ support_bot.metrics_url }}"
