---
- name: Deploy PostgreSQL exporter
  hosts: db_nodes
  gather_facts: false
  become: true

  vars_prompt:
    - name: ansible_become_password
      prompt: "BECOME password"
      private: true

  roles:
    - postgres_exporter
