---
nginx_package_name: "nginx"

nginx_config_owner: "root"
nginx_config_group: "root"
nginx_config_mode: "0644"

nginx_frontend_owner: "root"
nginx_frontend_group: "root"
nginx_frontend_mode: "0644"

nginx_site_config_src: "{{ playbook_dir }}/../files/nginx/default.conf"
nginx_index_src: "{{ playbook_dir }}/../files/nginx/index.html"
