---
node_role: "db"

postgres_service_name: "postgresql.service"
postgres_cluster_version: "17"
postgres_cluster_name: "main"
postgres_database_name: "supportdesk"
postgres_app_user: "supportdesk_user"

postgres_config_path: "/etc/postgresql/17/main/postgresql.conf"
postgres_hba_path: "/etc/postgresql/17/main/pg_hba.conf"
postgres_log_path: "/var/log/postgresql/*.log"

postgres_exporter_service_name: "prometheus-postgres-exporter.service"
postgres_exporter_metrics_url: "http://localhost:9187/metrics"

backup_script_path: "/usr/local/sbin/backup_supportdesk.sh"
backup_dir: "/var/backups/postgresql/supportdesk"
backup_latest_dump_path: "/var/backups/postgresql/supportdesk/latest.dump"
backup_service_name: "backup-supportdesk.service"
backup_timer_name: "backup-supportdesk.timer"
backup_retention_days: 7
backup_timer_on_calendar: "*-*-* 03:15:00"

promtail_config_template: "db-promtail.yml.j2"
promtail_config_path: "/etc/promtail/config.yml"
promtail_positions_path: "/var/lib/promtail/positions.yaml"

db_expected_services:
  - "{{ postgres_service_name }}"
  - "{{ postgres_exporter_service_name }}"
  - "{{ promtail_service_name }}"
  - "{{ node_exporter_service_name }}"
