---
node_role: "web"

nginx_service_name: "nginx.service"
nginx_web_root: "/var/www/html"
nginx_index_path: "/var/www/html/index.html"
nginx_site_config_path: "/etc/nginx/sites-available/default"

nginx_listen_port: "{{ web_http_port }}"
nginx_server_name: "_"

nginx_backend_host: "{{ app_ip }}"
nginx_backend_port: "{{ app_api_port }}"

nginx_client_max_body_size: "1m"
nginx_proxy_connect_timeout: "3s"
nginx_proxy_send_timeout: "30s"
nginx_proxy_read_timeout: "30s"

nginx_health_url: "http://localhost/"
nginx_api_health_url: "http://localhost/api/v1/health"

promtail_config_template: "web-promtail.yml.j2"
promtail_config_path: "/etc/promtail/config.yml"
promtail_positions_path: "/var/lib/promtail/positions.yaml"

nginx_log_paths:
  - "/var/log/nginx/*.log"

web_expected_services:
  - "{{ nginx_service_name }}"
  - "{{ promtail_service_name }}"
  - "{{ node_exporter_service_name }}"
