---
app_compose_owner: "root"
app_compose_group: "root"
app_compose_dir_mode: "0755"

app_compose_file_owner: "root"
app_compose_file_group: "root"
app_compose_file_mode: "0644"

app_compose_env_owner: "root"
app_compose_env_group: "root"
app_compose_env_mode: "0600"

app_compose_log_owner: "pelmel"
app_compose_log_group: "adm"
app_compose_log_dir_mode: "2750"
app_compose_log_file_mode: "0640"

app_compose_required_env_files:
  - ".env"
  - ".env.bot"

app_compose_required_files:
  - "docker-compose.yml"
  - ".dockerignore"

app_compose_log_directories:
  - "{{ app_log_dir }}"
  - "{{ bot_log_dir }}"

app_compose_log_files:
  - "{{ app_log_dir }}/app.log"
  - "{{ bot_log_dir }}/support-bot.log"
