---
prometheus_config_src: "{{ playbook_dir }}/../files/prometheus/prometheus.yml"
prometheus_rules_src: "{{ playbook_dir }}/../files/prometheus/supportdesk.rules.yml"

prometheus_config_owner: "root"
prometheus_config_group: "root"
prometheus_config_mode: "0644"

prometheus_rules_owner: "root"
prometheus_rules_group: "root"
prometheus_rules_mode: "0644"

prometheus_ready_retries: 10
prometheus_ready_delay: 3
