---
postgres_backup_script_src: "{{ playbook_dir }}/../files/postgres_backup/backup_supportdesk.sh"
postgres_backup_service_src: "{{ playbook_dir }}/../files/postgres_backup/backup-supportdesk.service"
postgres_backup_timer_src: "{{ playbook_dir }}/../files/postgres_backup/backup-supportdesk.timer"

postgres_backup_script_owner: "root"
postgres_backup_script_group: "postgres"
postgres_backup_script_mode: "0750"

postgres_backup_unit_owner: "root"
postgres_backup_unit_group: "root"
postgres_backup_unit_mode: "0644"

postgres_backup_dir_owner: "postgres"
postgres_backup_dir_group: "postgres"
postgres_backup_dir_mode: "0750"

postgres_backup_require_latest_dump: false
