[control]
admin ansible_connection=local

[web_nodes]
web ansible_host=192.168.85.131

[app_nodes]
app ansible_host=192.168.85.133

[log_nodes]
log ansible_host=192.168.85.135

[monitor_nodes]
monitor ansible_host=192.168.85.137

[managed:children]
web_nodes
app_nodes
log_nodes
monitor_nodes

[all:vars]
ansible_user=pelmel
ansible_python_interpreter=/usr/bin/python3
